"""tests/test_colab_gate.py — the Colab package-set gate's pure rules.

Every test here is offline and venv-free: the gate is deliberately split so
manifest parsing, the closure intersection, the requirement walk, the AST
import scan and the verdict are pure functions the suite can pin. The parts
that need a network or a throwaway venv (the live fetch, `pip --dry-run`, the
import probe) are exercised by running `verify_install F` for real.
"""

from __future__ import annotations

import json
import textwrap

import pytest

from heart.checks import colab_gate as cg


# --------------------------------------------------------------------------
# manifest parsing
# --------------------------------------------------------------------------


MANIFEST_SAMPLE = textwrap.dedent(
    """\
    # Do not modify this file directly; it is generated by a script.
    #  $ python3 -m pip freeze

    absl-py==1.4.0
    SQLAlchemy==2.0.52
    typing_extensions==4.16.0
    requests[socks]==2.32.3
    torch @ https://download.pytorch.org/whl/cu124/torch-2.8.0.whl
    some-vcs-package @ git+https://github.com/x/y@main
    -e /content/editable
    unpinned-package
    optax==0.2.8
    """
)


def test_manifest_parsing_keeps_pins_and_normalises_names():
    packages = cg.parse_manifest(MANIFEST_SAMPLE)

    assert packages["absl-py"] == "1.4.0"
    assert packages["optax"] == "0.2.8"
    # PEP 503: case folded, separators unified.
    assert packages["sqlalchemy"] == "2.0.52"
    assert packages["typing-extensions"] == "4.16.0"
    # Extras are not part of the name.
    assert packages["requests"] == "2.32.3"


def test_manifest_parsing_skips_everything_that_is_not_a_pin():
    packages = cg.parse_manifest(MANIFEST_SAMPLE)

    # Direct references and VCS installs name no installable version.
    assert "torch" not in packages
    assert "some-vcs-package" not in packages
    # Editables, comments, blanks and bare names are not pins either.
    assert "editable" not in packages
    assert "unpinned-package" not in packages
    assert not any(name.startswith("#") for name in packages)


def test_vendored_snapshot_parses_and_carries_its_fetch_date():
    text = cg.SNAPSHOT_PATH.read_text()
    packages = cg.parse_manifest(text)

    assert len(packages) > 500
    assert cg._snapshot_date(text) is not None
    # The package set the gate exists to reason about.
    assert "optax" in packages and "xxhash" in packages and "jax" in packages
    for absent in ("corner", "emcee", "dynesty", "blackjax", "nautilus-sampler"):
        assert absent not in packages, f"{absent} is not shipped by Colab"


# --------------------------------------------------------------------------
# manifest fallback order
# --------------------------------------------------------------------------


def _failing_fetch():
    raise OSError("no network in the unit suite")


def test_manifest_prefers_the_live_fetch_and_refreshes_the_cache(tmp_path):
    cache = tmp_path / "colab_pip_freeze.txt"

    packages, source, date, notes = cg.load_manifest(
        cache, fetcher=lambda: MANIFEST_SAMPLE
    )

    assert source == "live"
    assert date is not None
    assert notes == []
    assert packages["optax"] == "0.2.8"
    # The live copy is cached so the next offline run reads today's manifest
    # rather than falling all the way back to the vendored snapshot.
    assert cg.parse_manifest(cache.read_text())["optax"] == "0.2.8"


def test_manifest_falls_back_to_the_cache_when_the_fetch_fails(tmp_path):
    cache = tmp_path / "colab_pip_freeze.txt"
    cache.write_text("cached-only==9.9.9\n")

    packages, source, date, notes = cg.load_manifest(cache, fetcher=_failing_fetch)

    assert source == "cache"
    assert packages == {"cached-only": "9.9.9"}
    assert date is not None
    assert any("live fetch failed" in note for note in notes)


def test_manifest_falls_back_to_the_snapshot_when_there_is_no_cache(tmp_path):
    snapshot = tmp_path / "snapshot.txt"
    snapshot.write_text(
        "# source: googlecolab/backend-info pip-freeze.txt fetched 2026-09-15\n"
        "snapshot-only==1.2.3\n"
    )

    packages, source, date, notes = cg.load_manifest(
        tmp_path / "missing-cache.txt", snapshot_path=snapshot, fetcher=_failing_fetch
    )

    assert source == "snapshot"
    assert date == "2026-09-15"
    assert packages == {"snapshot-only": "1.2.3"}


def test_an_empty_live_manifest_is_not_trusted(tmp_path):
    """A 200 with an empty body must not seed an empty Colab."""
    packages, source, _, notes = cg.load_manifest(
        tmp_path / "missing-cache.txt", fetcher=lambda: ""
    )

    assert source == "snapshot"
    assert len(packages) > 500
    assert any("zero pins" in note for note in notes)


# --------------------------------------------------------------------------
# closure intersection
# --------------------------------------------------------------------------


def test_closure_intersection_keeps_colab_packages_and_drops_the_pyauto_stack():
    closure = {
        "autolens": "2026.9.1.1",
        "autofit": "2026.9.1.1",
        "autonerves": "2026.9.1.1",
        "autoarray": "2026.9.1.1",
        "autogalaxy": "2026.9.1.1",
        "numpy": "2.3.0",
        "optax": "0.3.0",
        "corner": "2.2.2",
    }
    manifest = {"numpy": "2.1.3", "optax": "0.2.8", "jax": "0.11.1"}

    assert cg.colab_intersection(closure, manifest) == ["numpy", "optax"]


def test_pyauto_packages_are_never_seeded_even_if_colab_shipped_them():
    """Defensive: the setup cell owns the PyAuto install, the seed never does."""
    manifest = {"autolens": "2020.1.1", "numpy": "2.1.3"}

    assert cg.colab_intersection({"autolens": "2026.9.1.1", "numpy": "2.3.0"}, manifest) == [
        "numpy"
    ]


def test_dry_run_report_is_parsed_out_of_noisy_pip_stdout():
    payload = {
        "install": [
            {"metadata": {"name": "NumPy", "version": "2.3.0"}},
            {"metadata": {"name": "corner", "version": "2.2.2"}},
        ]
    }
    stdout = "WARNING: a resolver warning reached stdout\n" + json.dumps(payload)

    assert cg.parse_dry_run_report(stdout) == {"numpy": "2.3.0", "corner": "2.2.2"}


# --------------------------------------------------------------------------
# requirement walk
# --------------------------------------------------------------------------


@pytest.fixture
def fake_dists():
    """A fabricated distribution graph: requires + installed versions."""
    requires = {
        "autofit": [
            "numpy>=2.0",
            "corner",
            "xxhash<=3.4.1",
            "dynesty==2.1.5",
            'optax>=0.2.5; sys_platform != "darwin"',
            'anesthetic>=2.9.0; extra == "optional"',
            'windows-only-thing; sys_platform == "win32"',
        ],
        "numpy": [],
        "xxhash": [],
    }
    installed = {"autofit": "2026.9.1.1", "numpy": "2.1.3", "xxhash": "4.0.1"}
    return requires, installed


def walk(fake_dists, manifest, install=None):
    requires, installed = fake_dists
    return cg.walk_requirements(
        ["autofit"],
        manifest,
        installed_version=lambda name: installed.get(cg.normalise(name)),
        requirements=lambda name: requires.get(cg.normalise(name), []),
        install=install,
    )


def test_walk_separates_colab_provided_missing_and_conflicting(fake_dists):
    manifest = {"numpy": "2.1.3", "xxhash": "4.0.1", "optax": "0.2.8"}

    result = walk(fake_dists, manifest)

    missing = {entry["name"] for entry in result["missing_declared"]}
    requested = {entry["name"] for entry in result["colab_installed"]}
    conflicts = {entry["name"]: entry for entry in result["version_conflict"]}

    # Absent AND not shipped by Colab: the hole the --no-deps bootstrap leaves.
    assert missing == {"corner", "dynesty"}
    # Absent but Colab ships it: install Colab's pin, not the declared floor.
    assert requested == {"optax"}
    assert result["colab_installed"][0]["version"] == "0.2.8"
    # Installed, but outside what autofit declares.
    assert set(conflicts) == {"xxhash"}
    assert conflicts["xxhash"]["installed"] == "4.0.1"
    assert conflicts["xxhash"]["specifier"] == "<=3.4.1"
    assert conflicts["xxhash"]["required_by"] == ["autofit"]


def test_walk_skips_extra_markers_and_false_environment_markers(fake_dists):
    result = walk(fake_dists, {"numpy": "2.1.3", "xxhash": "4.0.1", "optax": "0.2.8"})

    names = {entry["name"] for entry in result["missing_declared"]}
    # Behind `extra == "optional"`: not part of a plain `pip install autofit`.
    assert "anesthetic" not in names
    # Behind a marker that is false on Colab (always linux).
    assert "windows-only-thing" not in names


def test_walk_records_who_declared_a_missing_requirement(fake_dists):
    result = walk(fake_dists, {})

    corner = next(e for e in result["missing_declared"] if e["name"] == "corner")
    assert corner["required_by"] == ["autofit"]


def test_walk_continues_through_packages_it_installs_from_colab():
    requires = {
        "autofit": ["mid-package"],
        "mid-package": ["leaf-package"],
        "leaf-package": [],
    }
    installed = {"autofit": "1.0"}
    installs: list[list[str]] = []

    def install(pins):
        installs.append(list(pins))
        for pin in pins:
            name, _, version = pin.partition("==")
            installed[cg.normalise(name)] = version
        return True, ""

    result = cg.walk_requirements(
        ["autofit"],
        {"mid-package": "3.0"},
        installed_version=lambda name: installed.get(cg.normalise(name)),
        requirements=lambda name: requires.get(cg.normalise(name), []),
        install=install,
    )

    # mid-package installed from Colab's pin, then walked, exposing leaf-package
    # — which Colab does NOT ship, so it surfaces as a real hole.
    assert installs == [["mid-package==3.0"]]
    assert [e["name"] for e in result["colab_installed"]] == ["mid-package"]
    assert [e["name"] for e in result["missing_declared"]] == ["leaf-package"]
    assert result["rounds"] >= 2


def test_walk_reports_a_colab_pin_that_will_not_install():
    def install(pins):
        return False, "ERROR: no matching distribution"

    result = cg.walk_requirements(
        ["autofit"],
        {"broken-package": "1.0"},
        installed_version=lambda name: {"autofit": "1.0"}.get(cg.normalise(name)),
        requirements=lambda name: ["broken-package"] if name == "autofit" else [],
        install=install,
    )

    assert [e["name"] for e in result["missing_declared"]] == ["broken-package"]
    assert "no matching distribution" in result["missing_declared"][0]["note"]


# --------------------------------------------------------------------------
# AST import scan
# --------------------------------------------------------------------------


def test_scanner_finds_imports_at_any_depth_and_marks_guarding():
    source = textwrap.dedent(
        """\
        import numpy as np
        from astropy.io import fits


        def plot(samples):
            import corner            # the lazy import that detonates on Colab

            return corner.corner(samples)


        def optional():
            try:
                import zeus
            except ImportError:
                zeus = None
            return zeus


        def broadly_guarded():
            try:
                import hmf
            except Exception:
                return None


        def bare_guard():
            try:
                import colossus
            except:  # noqa: E722
                return None
        """
    )

    found = cg.scan_imports_source(source, "autofit/plot.py")
    by_name = {name: (line, guarded) for name, line, guarded in found}

    assert by_name["numpy"] == (1, False)
    # `from a.b import c` is attributed to the top-level distribution module.
    assert by_name["astropy"] == (2, False)
    # Function-level and unguarded: exactly the corner case.
    assert by_name["corner"] == (6, False)
    # try/except ImportError, try/except Exception and a bare except all guard.
    assert by_name["zeus"][1] is True
    assert by_name["hmf"][1] is True
    assert by_name["colossus"][1] is True


def test_scanner_excludes_relative_imports():
    found = cg.scan_imports_source(
        "from . import mask\nfrom ..operators import transformer\n", "autoarray/x.py"
    )

    assert found == []


def test_scanner_does_not_treat_except_or_finally_bodies_as_guarded():
    source = textwrap.dedent(
        """\
        try:
            import fast_thing
        except ImportError:
            import slow_thing
        else:
            import else_thing
        finally:
            import finally_thing
        """
    )

    guarded = {name: g for name, _, g in cg.scan_imports_source(source, "x.py")}

    assert guarded["fast_thing"] is True
    # A fallback import is the thing that must work, so it is not guarded.
    assert guarded["slow_thing"] is False
    assert guarded["else_thing"] is False
    assert guarded["finally_thing"] is False


def test_scanner_survives_a_file_it_cannot_parse():
    assert cg.scan_imports_source("def broken(:\n", "x.py") == []


def test_package_scan_drops_stdlib_pyauto_and_dunder_future(tmp_path):
    package = tmp_path / "autofit"
    (package / "sub").mkdir(parents=True)
    (package / "__init__.py").write_text(
        "from __future__ import annotations\n"
        "import os\nimport json\nimport pathlib\n"
        "import autoarray\nimport autolens\n"
        "import numpy\n"
    )
    (package / "sub" / "deep.py").write_text("def f():\n    import corner\n")

    sites = cg.scan_package_imports({"autofit": package})

    assert set(sites) == {"numpy", "corner"}
    # The site is reported repo-relative so a FAIL line points at a real file.
    assert sites["corner"][0]["file"] == "autofit/sub/deep.py"
    assert sites["corner"][0]["line"] == 2
    assert sites["corner"][0]["guarded"] is False


# --------------------------------------------------------------------------
# verdict
# --------------------------------------------------------------------------


def _verdict(**kwargs):
    base = dict(
        missing_declared=[],
        version_conflict=[],
        import_failures_unguarded=[],
        import_failures_guarded=[],
        constructor_failures=[],
    )
    base.update(kwargs)
    return cg.verdict(**base)


def test_clean_environment_passes():
    result = _verdict()

    assert result["ok"] is True
    assert result["fails"] == []


def test_an_unguarded_import_failure_fails_the_gate():
    result = _verdict(
        import_failures_unguarded=[
            {
                "module": "corner",
                "error": "ModuleNotFoundError: No module named 'corner'",
                "sites": [
                    {
                        "file": "autofit/non_linear/plot/samples_plotters.py",
                        "line": 95,
                        "guarded": False,
                    }
                ],
            }
        ],
        imported_modules=["corner"],
    )

    assert result["ok"] is False
    assert result["fails"] == [
        "corner (autofit/non_linear/plot/samples_plotters.py:95)"
    ]


def test_a_guarded_import_failure_is_only_a_warning():
    result = _verdict(
        import_failures_guarded=[
            {"module": "hmf", "error": "ModuleNotFoundError", "sites": [{}]}
        ]
    )

    assert result["ok"] is True
    assert any("hmf" in warn for warn in result["warns"])


def test_a_constructor_failure_fails_the_gate():
    result = _verdict(
        constructor_failures=[
            {"name": "Emcee", "error": "ModuleNotFoundError: No module named 'emcee'"}
        ]
    )

    assert result["ok"] is False
    assert "af.Emcee()" in result["fails"][0]


def test_a_missing_declared_dependency_fails_only_when_it_is_imported():
    imported = _verdict(
        missing_declared=[
            {"name": "corner", "required_by": ["autofit"], "specifier": ""}
        ],
        imported_modules=["corner", "numpy"],
    )
    never_imported = _verdict(
        missing_declared=[
            {"name": "gprof2dot", "required_by": ["autofit"], "specifier": ""}
        ],
        imported_modules=["corner", "numpy"],
    )

    assert imported["ok"] is False
    assert "corner" in imported["fails"][0]
    assert never_imported["ok"] is True
    assert any("gprof2dot" in warn for warn in never_imported["warns"])


def test_missing_dependency_matching_handles_dist_vs_module_names():
    """`scikit-learn` is imported as `sklearn`; the FAIL rule must still fire."""
    result = _verdict(
        missing_declared=[
            {"name": "scikit-learn", "required_by": ["autoarray"], "specifier": ""}
        ],
        imported_modules=["sklearn"],
    )

    assert result["ok"] is False


def test_version_conflicts_and_closure_gaps_are_warnings_only():
    result = _verdict(
        version_conflict=[
            {
                "name": "xxhash",
                "installed": "4.0.1",
                "specifier": "<=3.4.1",
                "required_by": ["autofit"],
            }
        ],
        closure_not_on_colab=["corner", "emcee"],
    )

    assert result["ok"] is True
    assert any("xxhash" in warn for warn in result["warns"])
    assert any("corner" in warn for warn in result["warns"])


def test_accepted_missing_downgrades_a_fail_to_a_warning():
    unguarded = [
        {
            "module": "corner",
            "error": "ModuleNotFoundError",
            "sites": [{"file": "autofit/plot.py", "line": 95, "guarded": False}],
        }
    ]

    blocking = _verdict(import_failures_unguarded=unguarded, imported_modules=["corner"])
    accepted = _verdict(
        import_failures_unguarded=unguarded,
        imported_modules=["corner"],
        accepted_missing=[{"name": "corner", "reason": "documented exemption"}],
    )

    assert blocking["ok"] is False
    assert accepted["ok"] is True
    assert accepted["accepted"] == [
        {"name": "corner", "kind": "unguarded import", "reason": "documented exemption"}
    ]
    assert any("documented exemption" in warn for warn in accepted["warns"])


def test_accepted_missing_is_matched_on_the_normalised_name():
    result = _verdict(
        missing_declared=[
            {"name": "nautilus-sampler", "required_by": ["autofit"], "specifier": ""}
        ],
        imported_modules=["nautilus"],
        accepted_missing=[{"name": "Nautilus_Sampler", "reason": "why"}],
    )

    assert result["ok"] is True


def test_detail_line_names_the_first_failures_then_counts_the_rest():
    fails = [f"pkg{i} (autofit/x.py:{i})" for i in range(6)]

    detail = cg.format_detail(fails)

    assert detail.startswith("colab gate: pkg0 (autofit/x.py:0); pkg1")
    assert detail.endswith("+3 more")
    assert "|" not in detail, "the RESULTS row is pipe-delimited"


# --------------------------------------------------------------------------
# config file
# --------------------------------------------------------------------------


def test_shipped_config_accepts_exactly_the_three_argued_exemptions():
    """The shipped exemption list, read from the real file the gate loads.

    Three of the five library-side holes the gate found are not notebook
    paths: `colossus` and `hmf` (the line-of-sight tooling in
    autolens/lens/los.py) and `mcp` (autofit/mcp/server.py, the MCP server
    entry point). Anything else appearing here is a hole in the `--no-deps`
    bootstrap being quietened rather than fixed, which is what the config
    file's own header forbids — so the set is asserted exactly, not as a
    subset.
    """
    config = cg.load_config(cg.CONFIG_PATH)

    assert {entry["name"] for entry in config["accepted_missing"]} == {
        "colossus",
        "hmf",
        "mcp",
    }
    # A silent exemption is the failure mode the reason field exists to
    # prevent: it travels into the JSON report next to the accepted name.
    for entry in config["accepted_missing"]:
        assert entry.get("reason", "").strip(), entry["name"]


def test_shipped_config_reads_identically_without_pyyaml():
    # `verify` runs inside the simulated venv, which need not have PyYAML, so
    # the fallback parser is what reads this file in the run that matters.
    # Anything the real file uses that only PyYAML understands would silently
    # drop an exemption there.
    parsed = cg._parse_config_fallback(cg.CONFIG_PATH.read_text())

    assert parsed == cg.load_config(cg.CONFIG_PATH)


def test_config_is_readable_without_pyyaml(tmp_path):
    """`verify` runs inside the simulated venv, which need not have PyYAML."""
    path = tmp_path / "colab_gate.yaml"
    path.write_text(
        "# a comment\n"
        "accepted_missing:\n"
        "  - name: corner\n"
        "    reason: exempt for a reason\n"
        "  - name: emcee\n"
        "    reason: another reason\n"
    )

    parsed = cg._parse_config_fallback(path.read_text())

    assert parsed["accepted_missing"] == [
        {"name": "corner", "reason": "exempt for a reason"},
        {"name": "emcee", "reason": "another reason"},
    ]


def test_missing_config_is_not_an_error(tmp_path):
    assert cg.load_config(tmp_path / "nope.yaml") == {"accepted_missing": []}


def test_walk_completes_a_no_deps_install_from_colabs_own_package_set():
    """The IPython/pickleshare regression.

    The seed installs the closure ∩ manifest `--no-deps`, so a seeded package's
    own runtime dependencies only land if the PyAuto closure happened to need
    them too. Colab ships IPython 7.34.0, which needs pickleshare, and nothing
    in the autolens closure does — so `import jax` (which reaches IPython via
    its Colab debugger) died on a package Colab has always had. Colab is
    internally consistent; the simulation has to be too.
    """
    requires = {"ipython": ["pickleshare", "jedi>=0.16"], "pickleshare": [], "jedi": []}
    installed = {"ipython": "7.34.0"}
    manifest = {"pickleshare": "0.7.5", "jedi": "0.19.2"}

    def install(pins):
        for pin in pins:
            name, _, version = pin.partition("==")
            installed[cg.normalise(name)] = version
        return True, ""

    result = cg.walk_requirements(
        ["ipython"],
        manifest,
        installed_version=lambda name: installed.get(cg.normalise(name)),
        requirements=lambda name: requires.get(cg.normalise(name), []),
        install=install,
    )

    assert sorted(e["name"] for e in result["colab_installed"]) == ["jedi", "pickleshare"]
    assert installed["pickleshare"] == "0.7.5"
    # Nothing absent from the manifest is ever installed by the completion pass.
    assert result["missing_declared"] == []


def test_module_dist_candidates_inverts_the_alias_table():
    # A module whose distribution is named differently still has to be
    # recognisable in the Colab manifest.
    assert "scikit-learn" in cg.module_dist_candidates("sklearn")
    assert "pyyaml" in cg.module_dist_candidates("yaml")
    assert "nautilus-sampler" in cg.module_dist_candidates("nautilus")
    # The ordinary case: the module name is the distribution name.
    assert cg.module_dist_candidates("numba") == {"numba"}
